# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
  build-android:
    needs: install-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: Build Android Release
        run: |
          cd android && ./gradlew assembleRelease -PMYAPP_UPLOAD_STORE_PASSWORD='${{ secrets.KEYSTORE_PASSWORD }}' -PMYAPP_UPLOAD_KEY_PASSWORD='${{ secrets.KEYSTORE_PASSWORD }}'
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/
  build-ios:
    needs: install-and-test
    runs-on: [self-hosted, macos]
    steps:
      - name: make enviroment
        run: |
          - mkdir actions-runner && cd actions-runner
          - curl -O -L https://github.com/actions/runner/releases/download/v2.263.0/actions-runner-osx-x64-2.263.0.tar.gz
          - tar xzf ./actions-runner-osx-x64-2.263.0.tar.gz
          - ./config.sh --url https://github.com/IgorDePaula/RNTestGithubActions --token AAVT4SLYOWMMDJQTFWXAAX263OVLO
          - ./run.sh
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: Install pod dependencies
        run: |
          cd ios && pod install
      - name: Build app
        run: |
          xcodebuild -workspace RNTestGithubActionsp.xcworkspace -scheme RNTestGithubActions archive -archivePath RNTestGithubActions.xcarchive -allowProvisioningUpdates
          xcodebuild -exportArchive -archivePath ./RNTestGithubActions.xcarchive -exportPath . -exportOptionsPlist myapp/Info.plist
          mv myapp.ipa ../myapp.ipa
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: myapp.ipa
          path: ios/build/


